id = "coi"
name = "Coi"
version = "0.1.0"
schema_version = 1
authors = ["James Turner <james@calminferno.net>"]
description = "Language support for Coi - a component-based language for high-performance web applications"
repository = "https://github.com/jturner/zed-coi"

languages = ["languages/coi"]

[grammars.coi]
repository = "https://github.com/jturner/tree-sitter-coi"
rev = "77fc94fac03f38c8a9f776924d0e3134529ec643"
