id = "coi"
name = "Coi"
version = "0.2.0"
schema_version = 1
authors = ["James Turner <james@calminferno.net>"]
description = "Language support for Coi - a component-based language for high-performance web applications"
repository = "https://github.com/jturner/zed-coi"

languages = ["languages/coi"]

[grammars.coi]
repository = "https://github.com/jturner/tree-sitter-coi"
rev = "8cc0aea6473c12240bd9dc34408d6d24f2342ef2"
